mcCommandsList = [
    {
        "func": "trailingNumbers",
        "label": "Trailing Numbers",
        "category": "naming",
        "defaultChecked": True,
    },
    {
        "func": "duplicatedNames",
        "label": "Duplicated Names",
        "category": "naming",
        "defaultChecked": True,
    },
    {
        "func": "shapeNames",
        "label": "Shape Names",
        "category": "naming",
        "defaultChecked": True,
    },
    {
        "func": "namespaces",
        "label": "Namespaces",
        "category": "naming",
        "defaultChecked": True,
    },
    {
        "func": "layers",
        "label": "Layers",
        "category": "general",
        "defaultChecked": True,
    },
    {
        "func": "history",
        "label": "History",
        "category": "general",
        "defaultChecked": True,
    },
    {
        "func": "shaders",
        "label": "Shaders",
        "category": "general",
        "defaultChecked": True,
    },
    {
        "func": "unfrozenTransforms",
        "label": "Unfrozen Transforms",
        "category": "general",
        "defaultChecked": True,
    },
    {
        "func": "uncenteredPivots",
        "label": "Uncentered Pivots",
        "category": "general",
        "defaultChecked": True,
    },
    {
        "func": "parentGeometry",
        "label": "Parent Geometry",
        "category": "general",
        "defaultChecked": True,
    },
    {
        "func": "emptyGroups",
        "label": "Empty Groups",
        "category": "general",
        "defaultChecked": True,
    },
    {
        "func": "triangles",
        "label": "Triangles",
        "category": "topology",
        "defaultChecked": False,
    },
    {
        "func": "ngons",
        "label": "Ngons",
        "category": "topology",
        "defaultChecked": True,
    },
    {
        "func": "openEdges",
        "label": "Open Edges",
        "category": "topology",
        "defaultChecked": False,
    },
    {
        "func": "poles",
        "label": "Poles",
        "category": "topology",
        "defaultChecked": False,
    },
    {
        "func": "hardEdges",
        "label": "Hard Edges",
        "category": "topology",
        "defaultChecked": True,
    },
    {
        "func": "lamina",
        "label": "Lamina",
        "category": "topology",
        "defaultChecked": False,
    },
    {
        "func": "zeroAreaFaces",
        "label": "Zero Area Faces",
        "category": "topology",
        "defaultChecked": False,
    },
    {
        "func": "zeroLengthEdges",
        "label": "Zero Length Edges",
        "category": "topology",
        "defaultChecked": False,
    },
    {
        "func": "noneManifoldEdges",
        "label": "None Manifold Edges",
        "category": "topology",
        "defaultChecked": True,
    },
    {
        "func": "starlike",
        "label": "Starlike",
        "category": "topology",
        "defaultChecked": False,
    },
    {
        "func": "selfPenetratingUVs",
        "label": "Self Penetrating UVs",
        "category": "UVs",
        "defaultChecked": True,
    },
    {
        "func": "missingUVs",
        "label": "Missing UVs",
        "category": "UVs",
        "defaultChecked": True,
    },
    {
        "func": "uvRange",
        "label": "UV Range",
        "category": "UVs",
        "defaultChecked": True,
    },
    {
        "func": "crossBorder",
        "label": "Cross Border",
        "category": "UVs",
        "defaultChecked": True,
    },
    {
        "func": "onBorder",
        "label": "On Border",
        "category": "UVs",
        "defaultChecked": False,
    },
    {
        "func": "keyFrames",
        "label": "Key Frames",
        "category": "general",
        "defaultChecked": True,
    },
    {
        "func": "unknowns",
        "label": "Unknowns",
        "category": "general",
        "defaultChecked": True,
    },
    {
        "func": "uvSetName",
        "label": "UV Set Names",
        "category": "UVs",
        "defaultChecked": True,
    },
]
